# data.yaml
path: /content/drive/MyDrive/t_bank_logo_detection/prepared   # абсолютный путь к данным
train: images/train                                           # относительный путь к train изображениям
val: images/val                                               # относительный путь к val изображениям
test: images/test 

# Класс только один - логотип Т-банка
nc: 1
names: ['t-bank-logo']